/**
 * Every UI string and fixed spoken line, in one place, so Kannada and Hindi
 * can be added later. Lesson sentences come from src/lib/templates.ts.
 * (Imported by scripts/generate-audio.mjs too, so keep it free of app imports.)
 */

/** Fixed spoken lines. Each one gets pre-generated audio. */
export const VOICE = {
  look: "Look.",
  thisOne: "This one.",
  tryAgain: "Let’s try again.",
  tryAnother: "Let’s try another.",
  scheduleWatch: "First, let’s watch.",
  schedulePractise: "Now, let’s practise.",
  scheduleCheck: "Now, show me.",
  scheduleReward: "Reward time!",
  chooseReward: "Pick your reward.",
  rewardBubbles: "Bubbles.",
  rewardStars: "Star garden.",
  rewardFish: "Swimming fish.",
  boardFull: "You filled your board!",
  breakTime: "Break time.",
  ready: "Ready.",
  missedPrompt: "Let’s practise the ones you missed.",
  allDone: "All done. Great work!",
  newSticker: "You earned a sticker!",
} as const;

export const S = {
  appName: "DCCD Learning Studio",
  centre: "Dimensions Centre for Child Development",
  credit: "Built by DeadEnd Engineers",
  loading: "Getting ready…",

  child: {
    whoIsLearning: "Who is learning?",
    noLearners: "Ask a grown-up to add a learner.",
    switchLearner: "Change learner",
    lessons: "Lessons",
    stickerBook: "Sticker book",
    noStickers: "Stickers you earn will live here.",
    stars: (n: number) => `${n} ${n === 1 ? "star" : "stars"}`,
    status: {
      new: "New",
      "in-progress": "Keep going",
      mastered: "Mastered",
      "review-due": "Review",
      locked: "Locked",
    },
    lockedHint: "Unlocks after Can",
    open: (title: string) => `Open ${title}`,
    home: "Home",
    mute: "Mute",
    break: "Break",
    breakTitle: "Break time",
    breakBody: "Rest as long as you like.",
    ready: "Ready",
    schedule: { watch: "Watch", practise: "Practise", check: "Check", reward: "Reward" },
    scheduleLabel: "Lesson steps",
    first: "First",
    then: "Then",
    answerN: (n: number) => `answer ${n}`,
    tokens: (filled: number, size: number) => `${filled} of ${size} tokens`,
    back: "Back",
    next: "Next",
    replay: "Replay",
    startPractise: "Practise",
    chooseReward: "Pick your reward",
    rewards: { bubbles: "Bubbles", stars: "Star garden", fish: "Swimming fish" },
    keepGoing: "Keep going",
    missedTitle: "Practise the ones you missed?",
    missedYes: "Practise them",
    missedNo: "Go to reward",
    finish: "Finish",
    allDone: "All done",
    newSticker: "New sticker",
    cantLabel: "can’t",
    canLabel: "can",
    card: (name: string) => `The ${name}`,
    reviewTitle: "Review",
    chooseLearnerFirst: "Pick who is learning first.",
    notAvailable: "This lesson isn’t available.",
    noItems: "This lesson has no approved items yet. Ask a grown-up.",
    goHome: "Go home",
  },

  grownUp: {
    lockLabel: "Grown-ups: press and hold for 2 seconds",
    lockHint: "Press and hold (or hold Space) to open",
    area: "Grown-up area",
    backToChild: "Back to child view",
    tabs: { learners: "Learners", progress: "Progress", lessons: "Lessons", backup: "Backup" },
    notSecurity: "The lock keeps children out; it is not security. All data stays on this device.",
    defaultsNote: "Teaching defaults are starting points for DCCD’s clinicians to review.",

    learners: {
      title: "Learners",
      add: "Add learner",
      nickname: "Nickname",
      nicknameHelp: "Nickname only: no surnames, no photos.",
      avatar: "Avatar",
      save: "Save",
      cancel: "Cancel",
      rename: "Rename",
      delete: "Delete",
      deleteConfirm: (name: string) => `Delete ${name} and all of ${name}’s sessions? This cannot be undone.`,
      none: "No learners yet. Add one, or load the demo data from Backup.",
      settings: "Teaching settings",
      childSettings: "Child settings",
      calmMode: "Calm mode",
      calmHelp: "Only short fades; idle movement stops.",
      voiceOn: "Voice",
      watchAutoplay: "Watch step plays on by itself",
      voiceRate: "Voice speed",
      voiceRates: { "0.85": "Slower", "1": "Normal" },
      textSize: "Text size",
      textSizes: { regular: "Regular", large: "Large" },
      strategy: "Prompting strategy",
      strategies: { errorless: "Errorless (time delay)", "least-to-most": "Least-to-most" },
      delayStep: "Current time-delay step",
      delayReset: "Reset to 0 s",
      tokenBoardSize: "Token board size",
      tokensForPrompted: "Tokens for prompted answers",
      mastery: "Mastery criterion",
      masteryPercent: "Independent correct",
      masterySessions: "Consecutive sessions",
      pause: "Pause between trials",
      review: "Review mastered lessons after",
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
      canBeforeCant: "Teach Can before Can’t",
      canBeforeCantHelp: "Off lets this learner start Can’t straight away.",
      assign: "Assigned lessons",
      assignHelp: "Only assigned lessons appear in the child’s library.",
      seconds: (n: number) => `${n} s`,
    },

    progress: {
      title: "Progress",
      learner: "Learner",
      lesson: "Lesson",
      noSessions: "No sessions yet for this lesson.",
      summary: "Summary",
      trend: "Independent correct in Check",
      sessions: "Sessions",
      date: "Date",
      kind: "Type",
      independent: "Independent",
      prompts: "Prompt levels",
      promptLegend: "Independent / level 1 / 2 / 3",
      latency: "Avg. time to respond",
      breaks: "Breaks",
      bias: "Position bias (last 20 taps)",
      biasFlag: (side: string, pct: number) => `Flag: ${pct}% of taps on the ${side}. Check whether the child is choosing a side rather than the answer.`,
      biasOk: "No side bias.",
      biasNotEnough: (n: number) => `Only ${n} taps so far; the flag needs 20.`,
      left: "Left",
      right: "Right",
      print: "Print or save as PDF",
      status: "Status",
      delay: "Time delay",
      reportFor: (name: string) => `Progress report: ${name}`,
      generated: (d: string) => `Generated ${d}`,
    },

    lessons: {
      title: "Lessons",
      lesson: "Lesson",
      help: "Draft rows never reach a child. Answer is always the character who can’t.",
      verb: "Verb",
      optionA: "Option A",
      optionB: "Option B",
      answer: "Answer (can’t)",
      status: "Status",
      approved: "Approved",
      draft: "Draft",
      addRow: "Add row",
      deleteRow: "Delete row",
      deleteRowConfirm: (verb: string) => `Delete the row “${verb || "(no verb)"}”?`,
      reset: "Reset to DCCD deck",
      resetConfirm: (title: string) => `Replace every row in ${title} with DCCD’s original 10 items?`,
      importTitle: "Import CSV",
      importHelp: "Export your Google Sheet as CSV and paste it here. In the full build this syncs automatically.",
      importHeader: "Header: verb,optionA,optionB,answer,status",
      importPaste: "Paste CSV",
      importFile: "Or choose a .csv file",
      importCheck: "Check rows",
      importRowsOk: (n: number) => `${n} valid ${n === 1 ? "row" : "rows"}`,
      importRowsBad: (n: number) => `${n} ${n === 1 ? "row has" : "rows have"} errors and will be skipped`,
      importConfirm: (n: number, title: string) => `Add ${n} ${n === 1 ? "row" : "rows"} to ${title}`,
      imported: (n: number) => `Imported ${n} ${n === 1 ? "row" : "rows"}.`,
      line: "Line",
      problems: "Problems",
      rowInvalid: "Needs a verb and two different characters; hidden from children until fixed.",
    },

    backup: {
      title: "Backup",
      export: "Export all data (JSON)",
      import: "Import from JSON",
      importConfirm: "Replace all data on this device with the file’s contents?",
      importBad: "That file isn’t a valid backup:",
      imported: "Backup imported.",
      demo: "Load demo data",
      demoHelp: "Adds two demo learners with realistic sessions (one shows a right-side bias).",
      demoConfirm: "Add the two demo learners? Existing demo learners are replaced.",
      demoLoaded: "Demo data loaded.",
      clear: "Clear all data",
      clearConfirm: "Delete every learner, session and lesson edit on this device? Export first if you need a copy.",
      cleared: "All data cleared.",
      quota: "This device’s storage is full, so the latest changes may not be saved. Export a backup, then clear old data.",
      limits: [
        "All data stays in this browser on this device. Nothing is sent anywhere.",
        "The lock keeps children out; it is not security.",
        "Teaching defaults are starting points for DCCD’s clinicians to review.",
      ],
    },

    confirm: "Confirm",
    cancel: "Cancel",
  },
} as const;
