/**
 * Every UI string and fixed spoken line, in one place, so Kannada and Hindi
 * can be added later. Lesson sentences come from src/lib/templates.ts.
 * (Imported by scripts/generate-audio.mjs too, so keep it free of app imports.)
 */

/** Fixed spoken lines. Each one gets pre-generated audio. */
export const VOICE = {
  openBook: "Let’s read together.",
  lookAgain: "Let’s look again.",
  tryAnother: "Let’s try another.",
  quiz: "Now, show me.",
  allDone: "The end. Great reading!",
  newSticker: "You earned a sticker!",
} as const;

/** Voice speeds (playback rate on top of the already slow recording). */
export const SPEEDS = [
  [0.8, "Slower"],
  [1, "Normal"],
  [1.2, "Faster"],
] as const;

export const S = {
  appName: "DCCD Learning Studio",
  centre: "Dimensions Centre for Child Development",
  credit: "Built by DeadEnd Engineers",
  loading: "Getting ready…",

  child: {
    whoIsReading: "Who is reading today?",
    noLearners: "Ask a grown-up to add a reader.",
    switchLearner: "Change reader",
    books: "Your books",
    bookTitle: (polarity: "can" | "cant") => (polarity === "cant" ? "Who can’t?" : "Who can?"),
    stickerBook: "My stickers",
    noStickers: "Stickers you earn will live here.",
    status: {
      new: "New",
      "in-progress": "Keep going",
      mastered: "Mastered",
      "review-due": "Read again",
    },
    open: (title: string) => `Open ${title}`,
    openBook: "Open the book",
    home: "Home",
    mute: "Mute",
    speed: (label: string) => `Voice speed: ${label}`,
    sayAgain: "Say it again",
    turnPage: "Next page",
    page: (n: number, total: number) => `Page ${n} of ${total}`,
    theEnd: "The end",
    newSticker: "New sticker",
    finish: "Back to my books",
    cantLabel: "can’t",
    canLabel: "can",
    card: (name: string) => `The ${name}`,
    chooseLearnerFirst: "Pick who is reading first.",
    notAvailable: "This book isn’t available.",
    noItems: "This book has no pages yet. Ask a grown-up.",
    goHome: "Go home",
    grownUps: "Grown-ups",
  },

  grownUp: {
    area: "Grown-up area",
    backToChild: "Back to child view",
    tabs: { learners: "Children", progress: "Progress", lessons: "Books", backup: "Backup" },
    notSecurity: "All data stays on this device. Nothing is sent anywhere.",
    defaultsNote: "Teaching defaults are starting points for DCCD’s clinicians to review.",

    learners: {
      title: "Children",
      add: "Add a child",
      nickname: "Nickname",
      nicknameHelp: "Nickname only: no surnames, no photos.",
      avatar: "Pick a picture",
      save: "Save",
      cancel: "Cancel",
      rename: "Rename",
      delete: "Delete",
      deleteConfirm: (name: string) => `Delete ${name} and all of ${name}’s sessions? This cannot be undone.`,
      none: "No children yet. Add one, or load the demo data from Backup.",
      moreSettings: "More settings",
      childSettings: "Reading",
      settings: "Mastery and review",
      calmMode: "Calm mode",
      calmHelp: "Only short fades; idle movement stops.",
      voiceOn: "Voice",
      voiceRate: "Voice speed",
      textSize: "Text size",
      textSizes: { regular: "Regular", large: "Large" },
      mastery: "Mastery criterion",
      masteryPercent: "Independent correct",
      masterySessions: "Consecutive sessions",
      review: "Review mastered lessons after",
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
      assign: "Books on the shelf",
      assignHelp: "Only these books appear for this child.",
    },

    progress: {
      title: "Progress",
      learner: "Child",
      lesson: "Book",
      noSessions: "No sessions yet for this book.",
      summary: "Summary",
      trend: "Independent correct in Check",
      sessions: "Sessions",
      date: "Date",
      kind: "Type",
      independent: "Independent",
      prompts: "Prompt levels",
      promptLegend: "Independent / level 1 / 2 / 3",
      latency: "Avg. time to respond",
      breaks: "Breaks",
      bias: "Position bias (last 20 taps)",
      biasFlag: (side: string, pct: number) => `Flag: ${pct}% of taps on the ${side}. Check whether the child is choosing a side rather than the answer.`,
      biasOk: "No side bias.",
      biasNotEnough: (n: number) => `Only ${n} taps so far; the flag needs 20.`,
      left: "Left",
      right: "Right",
      print: "Print or save as PDF",
      status: "Status",
      reportFor: (name: string) => `Progress report: ${name}`,
      generated: (d: string) => `Generated ${d}`,
    },

    lessons: {
      book: "Book",
      help: "Each page asks one question. Tap a page to change it.",
      newPage: "New page",
      editPage: (verb: string) => `Edit the page “${verb}”`,
      deletePage: (verb: string) => `Delete the page “${verb}”`,
      deletePageConfirm: (verb: string) => `Delete the page “${verb || "(no action)"}”?`,
      hidden: "Hidden",
      needsFix: "Needs fixing",
      stepVerb: "1. What is the action?",
      verbPlaceholder: "fly",
      verbHelp: "One or two words, like “fly” or “climb a tree”.",
      stepPictures: "2. Tap two pictures",
      stepAnswer: (verb: string) => `3. Who can’t ${verb || "do it"}?`,
      pickTwoFirst: "Pick two pictures first.",
      preview: "What the child sees",
      showToChildren: "Show this page to children",
      savePage: "Save page",
      cancel: "Cancel",
      reset: "Reset to DCCD deck",
      resetConfirm: (title: string) => `Replace every page in ${title} with DCCD’s original 10?`,
      moreTools: "Import from a sheet",
      importTitle: "Import CSV",
      importHelp: "Export your Google Sheet as CSV and paste it here. In the full build this syncs automatically.",
      importHeader: "Header: verb,optionA,optionB,answer,status",
      importPaste: "Paste CSV",
      importFile: "Or choose a .csv file",
      importCheck: "Check rows",
      importRowsOk: (n: number) => `${n} valid ${n === 1 ? "row" : "rows"}`,
      importRowsBad: (n: number) => `${n} ${n === 1 ? "row has" : "rows have"} errors and will be skipped`,
      importConfirm: (n: number, title: string) => `Add ${n} ${n === 1 ? "page" : "pages"} to ${title}`,
      imported: (n: number) => `Imported ${n} ${n === 1 ? "page" : "pages"}.`,
      line: "Line",
      problems: "Problems",
    },

    backup: {
      title: "Backup",
      export: "Export all data (JSON)",
      import: "Import from JSON",
      importConfirm: "Replace all data on this device with the file’s contents?",
      importBad: "That file isn’t a valid backup:",
      imported: "Backup imported.",
      demo: "Load demo data",
      demoHelp: "Adds two demo learners with realistic sessions (one shows a right-side bias).",
      demoConfirm: "Add the two demo learners? Existing demo learners are replaced.",
      demoLoaded: "Demo data loaded.",
      clear: "Clear all data",
      clearConfirm: "Delete every learner, session and lesson edit on this device? Export first if you need a copy.",
      cleared: "All data cleared.",
      quota: "This device’s storage is full, so the latest changes may not be saved. Export a backup, then clear old data.",
      limits: [
        "All data stays in this browser on this device. Nothing is sent anywhere.",
        "Teaching defaults are starting points for DCCD’s clinicians to review.",
      ],
    },

    confirm: "Confirm",
    cancel: "Cancel",
  },
} as const;
